name: Bug Report
description: Report a defect in VBW
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        **Important**: If this is a security vulnerability, do NOT open an issue.
        Follow the [Security Policy](../../SECURITY.md) and email security@scqcs.dev.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear description of the bug.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the behavior.
      placeholder: |
        1. Run `vbw verify ...`
        2. Observe error ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened. Include error output if available.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: VBW Version
      description: Output of `vbw --version`
      placeholder: "vbw 0.1.0"
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux (x86_64)
        - Linux (aarch64)
        - macOS (x86_64)
        - macOS (Apple Silicon)
        - Other
    validations:
      required: true
